### ISSUE TITLE
Matrix inversion returning wrong results

### ISSUE THREAD

**Issue by merlzbert** [tomtuamnuq/compare-qiskit-ocean#4]
Hi Tom,

I also re-implemented the matrix inversion of M. Rogers and R. Singleton from "Floating-Point Calculations on a Quantum Annealer: Division and Matrix Inversion". When running my code I only found the correct solution for Test cases a) and b). 3x3 does not work either.

Therefore, I stumbled through Git and discovered your version. I also ran it and it gives the same wrong results for the other test cases. Do you have any idea why that could be? Using a different offset, etc?

Would be happy to hear back from you, if you ever managed to get it fully running, or have other insights.

Best,
Merlin

**Comment by tomtuamnuq** [comment]
Hi @merlzbert ,

unfortunately, I do not know why it did only work for the 2x2 test cases. 

I thought it could be a problem with the formulas in the paper or the quantum problem specification.
As offset `np.inner(Y, Y)` is used. Have not tried something else.

I have used the DWaveCliqueSampler and there are qubit chains to achieve the embedding of the dense problem with 15 qubits. However, the chains for the solution candidates with lowest energies seem to be okay (https://github.com/tomtuamnuq/compare-qiskit-ocean/blob/main/comparison/Ocean/LinearProgramming/Float/QUBO_Float%203x3.ipynb)

If you find a solution I would be happy to hear about it.

**Comment by merlzbert** [comment]
Thanks for your fast reply! I will let you know, if I find something!
